/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3_f2019027009;

/**
 *
 * @author Hina Iqbal
 */
public class PationtRegistration extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PationtRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Company = new javax.swing.JTextField();
        MYNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        FName = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DOB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JComboBox<>();
        MStatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PName = new javax.swing.JTextField();
        CNIC = new javax.swing.JTextField();
        Relation = new javax.swing.JTextField();
        MName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Tehsil = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField16 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField18 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Mobile = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ONumber = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jTextField56 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jTextField57 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jTextField58 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jTextField59 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jTextField60 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jTextField61 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jTextField62 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextField63 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jTextField64 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        button5 = new java.awt.Button();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jTextField67 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jTextField68 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jTextField69 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jTextField70 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jTextField71 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jTextField72 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jTextField73 = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jTextField74 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jTextField75 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        checkbox6 = new java.awt.Checkbox();
        checkbox7 = new java.awt.Checkbox();
        checkbox8 = new java.awt.Checkbox();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        checkbox5 = new java.awt.Checkbox();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel15.setText("Type");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, 681, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setText("Type");

        Type.setText("Ctrl +o rF9 to LOV");
        Type.setEnabled(false);
        Type.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TypeCaretUpdate(evt);
            }
        });
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        jLabel3.setText("Company");

        jLabel4.setText("Mr num");

        Company.setText("Ctrl +o rF9 to LOV");
        Company.setEnabled(false);
        Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyActionPerformed(evt);
            }
        });

        jLabel5.setText("Title");

        jLabel6.setText("Full Name");

        Title.setText("MR.");
        Title.setEnabled(false);

        FName.setText("Hint : Muhammad");
        FName.setEnabled(false);

        LName.setText("Ali");
        LName.setEnabled(false);
        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Age");

        DOB.setEnabled(false);

        jLabel8.setText("D.O.B");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year(s)" }));
        jComboBox2.setEnabled(false);

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Gender.setEnabled(false);

        MStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        MStatus.setEnabled(false);
        MStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MStatusActionPerformed(evt);
            }
        });

        jLabel9.setText("Gender");

        jLabel10.setText("Marital Status");

        jLabel11.setText("CNIC");

        jLabel12.setText("Contact Person");

        jLabel13.setText("Relation");

        PName.setText("Hint : Ali");
        PName.setEnabled(false);

        CNIC.setText("     -      -");

        Relation.setText("Ctrl +o rF9 to LOV");
        Relation.setEnabled(false);

        MName.setText("Anwar");
        MName.setEnabled(false);
        MName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNameActionPerformed(evt);
            }
        });

        jLabel14.setText("Type");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tehsil.setText("Ctrl +o rF9 to LOV");
        Tehsil.setEnabled(false);
        Tehsil.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TehsilCaretUpdate(evt);
            }
        });
        Tehsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TehsilActionPerformed(evt);
            }
        });
        jPanel6.add(Tehsil, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel17.setText("Address");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        Address.setText("Hint : Present Address");
        Address.setEnabled(false);
        jPanel6.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel28.setText("Tehsil");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField14.setText("Ctrl +o rF9 to LOV");
        jTextField14.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField14CaretUpdate(evt);
            }
        });
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel18.setText("Address");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField15.setText("jTextField1");
        jPanel7.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel29.setText("Tehsil");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField16.setText("Ctrl +o rF9 to LOV");
        jTextField16.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField16CaretUpdate(evt);
            }
        });
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel19.setText("Address");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField17.setText("jTextField1");
        jPanel8.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel30.setText("Tehsil");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField18.setText("Ctrl +o rF9 to LOV");
        jTextField18.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField18CaretUpdate(evt);
            }
        });
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel20.setText("Address");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField19.setText("jTextField1");
        jPanel9.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel31.setText("Tehsil");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 660, 50));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mobile.setText("Hint : 03001111111");
        Mobile.setEnabled(false);
        Mobile.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                MobileCaretUpdate(evt);
            }
        });
        Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileActionPerformed(evt);
            }
        });
        jPanel10.add(Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel21.setText("Other");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 15, -1, -1));

        jLabel22.setText("Email");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 15, 67, -1));

        ONumber.setText("Hint : 04268569893");
        ONumber.setEnabled(false);
        jPanel10.add(ONumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 12, 111, -1));

        Email.setText("Hint : Anwar@gmail.com");
        Email.setEnabled(false);
        jPanel10.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 12, 260, -1));

        jLabel36.setText("number");
        jPanel10.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel53.setText("Mobile ");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField56.setText("Ctrl +o rF9 to LOV");
        jTextField56.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField56CaretUpdate(evt);
            }
        });
        jTextField56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField56ActionPerformed(evt);
            }
        });
        jPanel18.add(jTextField56, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel67.setText("Address");
        jPanel18.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField57.setText("jTextField1");
        jPanel18.add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel68.setText("Tehsil");
        jPanel18.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField58.setText("Ctrl +o rF9 to LOV");
        jTextField58.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField58CaretUpdate(evt);
            }
        });
        jTextField58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField58ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField58, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel69.setText("Address");
        jPanel19.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField59.setText("jTextField1");
        jPanel19.add(jTextField59, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel70.setText("Tehsil");
        jPanel19.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField60.setText("Ctrl +o rF9 to LOV");
        jTextField60.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField60CaretUpdate(evt);
            }
        });
        jTextField60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField60ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel71.setText("Address");
        jPanel20.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField61.setText("jTextField1");
        jPanel20.add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel72.setText("Tehsil");
        jPanel20.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField62.setText("Ctrl +o rF9 to LOV");
        jTextField62.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField62CaretUpdate(evt);
            }
        });
        jTextField62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField62ActionPerformed(evt);
            }
        });
        jPanel21.add(jTextField62, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel73.setText("Address");
        jPanel21.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField63.setText("jTextField1");
        jPanel21.add(jTextField63, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel74.setText("Tehsil");
        jPanel21.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 660, 50));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel75.setText("Mobile NUmbeer");
        jPanel22.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jTextField64.setText("Ctrl +o rF9 to LOV");
        jTextField64.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField64CaretUpdate(evt);
            }
        });
        jTextField64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField64ActionPerformed(evt);
            }
        });
        jPanel22.add(jTextField64, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel76.setText("Other");
        jPanel22.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 15, -1, -1));

        jLabel77.setText("Email");
        jPanel22.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 15, 67, -1));

        jTextField65.setText("jTextField1");
        jPanel22.add(jTextField65, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 12, 111, -1));

        jTextField66.setText("jTextField1");
        jPanel22.add(jTextField66, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 12, 260, -1));

        jLabel78.setText("Type");
        jPanel22.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel17.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 670, 40));

        button5.setLabel("Order");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel17.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 10, 150, 40));

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField67.setText("Ctrl +o rF9 to LOV");
        jTextField67.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField67CaretUpdate(evt);
            }
        });
        jTextField67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField67ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField67, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel79.setText("Address");
        jPanel24.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField68.setText("jTextField1");
        jPanel24.add(jTextField68, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel80.setText("Tehsil");
        jPanel24.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField69.setText("Ctrl +o rF9 to LOV");
        jTextField69.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField69CaretUpdate(evt);
            }
        });
        jTextField69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField69ActionPerformed(evt);
            }
        });
        jPanel25.add(jTextField69, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel81.setText("Address");
        jPanel25.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField70.setText("jTextField1");
        jPanel25.add(jTextField70, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel82.setText("Tehsil");
        jPanel25.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField71.setText("Ctrl +o rF9 to LOV");
        jTextField71.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField71CaretUpdate(evt);
            }
        });
        jTextField71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField71ActionPerformed(evt);
            }
        });
        jPanel26.add(jTextField71, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel83.setText("Address");
        jPanel26.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField72.setText("jTextField1");
        jPanel26.add(jTextField72, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel84.setText("Tehsil");
        jPanel26.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField73.setText("Ctrl +o rF9 to LOV");
        jTextField73.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField73CaretUpdate(evt);
            }
        });
        jTextField73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField73ActionPerformed(evt);
            }
        });
        jPanel27.add(jTextField73, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel85.setText("Address");
        jPanel27.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 15, 60, -1));

        jTextField74.setText("jTextField1");
        jPanel27.add(jTextField74, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 12, 400, -1));

        jLabel86.setText("Tehsil");
        jPanel27.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 660, 50));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, 50));

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel87.setText("Mobile NUmbeer");
        jPanel28.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jTextField75.setText("Ctrl +o rF9 to LOV");
        jTextField75.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField75CaretUpdate(evt);
            }
        });
        jTextField75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField75ActionPerformed(evt);
            }
        });
        jPanel28.add(jTextField75, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 12, 121, -1));

        jLabel88.setText("Other");
        jPanel28.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 15, -1, -1));

        jLabel89.setText("Email");
        jPanel28.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 15, 67, -1));

        jTextField76.setText("jTextField1");
        jPanel28.add(jTextField76, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 12, 111, -1));

        jTextField77.setText("jTextField1");
        jPanel28.add(jTextField77, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 12, 260, -1));

        jLabel90.setText("Type");
        jPanel28.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        jPanel23.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 670, 40));

        checkbox6.setEnabled(false);
        checkbox6.setLabel("Govt. Employ");
        jPanel23.add(checkbox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        checkbox7.setEnabled(false);
        checkbox7.setLabel("Died");
        jPanel23.add(checkbox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        checkbox8.setEnabled(false);
        checkbox8.setLabel("Confidental");
        jPanel23.add(checkbox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        button6.setLabel("Reports");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel23.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, -1));

        button7.setLabel("Print Card");
        jPanel23.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, -1));

        button8.setEnabled(false);
        button8.setLabel("Attach Picture");
        jPanel23.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 100, -1));

        button9.setLabel("New");
        jPanel23.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 70, -1));

        button10.setLabel("Edit");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        jPanel23.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 20, 70, -1));

        checkbox5.setEnabled(false);
        checkbox5.setLabel("Active");
        jPanel23.add(checkbox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(MYNum, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(MStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addComponent(CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(PName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13)
                        .addGap(16, 16, 16)
                        .addComponent(Relation, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MYNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Relation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 98, -1, 431));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MStatusActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TypeActionPerformed

    private void TypeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TypeCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeCaretUpdate

    private void MNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNameActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void TehsilCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TehsilCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_TehsilCaretUpdate

    private void TehsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TehsilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TehsilActionPerformed

    private void jTextField14CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField14CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14CaretUpdate

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField16CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField16CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16CaretUpdate

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField18CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField18CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18CaretUpdate

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileActionPerformed

    private void MobileCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_MobileCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileCaretUpdate

    private void jTextField56CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField56CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField56CaretUpdate

    private void jTextField56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField56ActionPerformed

    private void jTextField58CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField58CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField58CaretUpdate

    private void jTextField58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField58ActionPerformed

    private void jTextField60CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField60CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField60CaretUpdate

    private void jTextField60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField60ActionPerformed

    private void jTextField62CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField62CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField62CaretUpdate

    private void jTextField62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField62ActionPerformed

    private void jTextField64CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField64CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField64CaretUpdate

    private void jTextField64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField64ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void jTextField67CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField67CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField67CaretUpdate

    private void jTextField67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField67ActionPerformed

    private void jTextField69CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField69CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField69CaretUpdate

    private void jTextField69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField69ActionPerformed

    private void jTextField71CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField71CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField71CaretUpdate

    private void jTextField71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField71ActionPerformed

    private void jTextField73CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField73CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField73CaretUpdate

    private void jTextField73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField73ActionPerformed

    private void jTextField75CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField75CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField75CaretUpdate

    private void jTextField75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField75ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PationtRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PationtRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PationtRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PationtRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PationtRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField CNIC;
    private javax.swing.JTextField Company;
    private javax.swing.JComboBox<String> DOB;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FName;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField MName;
    private javax.swing.JComboBox<String> MStatus;
    private javax.swing.JTextField MYNum;
    private javax.swing.JTextField Mobile;
    private javax.swing.JTextField ONumber;
    private javax.swing.JTextField PName;
    private javax.swing.JTextField Relation;
    private javax.swing.JTextField Tehsil;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField Type;
    private java.awt.Button button10;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Checkbox checkbox5;
    private java.awt.Checkbox checkbox6;
    private java.awt.Checkbox checkbox7;
    private java.awt.Checkbox checkbox8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    // End of variables declaration//GEN-END:variables
}
